-- ==========================================================================
--  seed_config.sql - Conteudo das 3 tabelas de CONFIGURACAO (001B, 002B, 002N)
--  --------------------------------------------------------------------------
--  Gerado a partir do ambiente atual (COE_IA @ sef01d). Rode depois do
--  schema.sql quando estiver subindo num banco NOVO. As tabelas de dados
--  (001A/002A) nao entram aqui: sao preenchidas pelo proprio pipeline.
--
--  DATA_INI fica com a data da carga (SYSDATE), e nao com a data original,
--  para que tudo passe a valer a partir da implantacao.
-- ==========================================================================

-- --- 001B: palavras-chave dos atos de pessoal ---------------------------
DELETE FROM COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_001B";
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_001B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (1, 'nomear', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_001B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (2, 'exonerar', TRUNC(SYSDATE));

-- --- 002B: pre-filtro do monitor ---------------------------------------
DELETE FROM COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B";
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (1, 'fazenda', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (2, 'sefaz', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (3, 'rioprevid', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (4, 'fundo unico', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (5, 'tesouro', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (6, 'supcc', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (7, 'supat', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (8, 'supbf', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (9, 'supct', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (10, 'supfinf', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (11, 'supdief', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (12, 'supaqtic', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (13, 'receita estadual', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (14, 'subsecretaria de estado de receita', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (15, 'conselho de contribuintes', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (16, 'junta de revisao', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (17, 'auditor fiscal', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (18, 'auditoria fiscal', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (19, 'tributa', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (20, 'icms', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (21, 'itd', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (22, 'ipva', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (23, 'inscricao estadual', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (24, 'controle interno', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (25, 'corregedoria', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (26, 'credito suplementar', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (27, 'dotacao orcamentaria', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (28, 'orcamento', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (29, 'ponto facultativo', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (30, 'expediente', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (31, 'feriado', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (32, 'recesso', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (33, 'suspensao de expediente', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (34, 'horario especial', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002B" (ID, PALAVRA_CHAVE, DATA_INI) VALUES (35, 'calamidade', TRUNC(SYSDATE));

-- --- 002N: nomes monitorados -------------------------------------------
DELETE FROM COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N";
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (1, 'Guilherme Mercês', 'Secretário de Estado de Fazenda', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (2, 'Lucas Antonio Gonçalves Salvetti', 'Chefe de Gabinete', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (3, 'Roberto Gomides de Barros Filho', 'Subsecretaria-Geral de Fazenda', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (4, 'Carlos Alberto Cincurá de Andrade', 'Subsecretaria de Estado de Receita', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (5, 'Edson Tadeu Teixeira Amantea', 'Subsecretaria Adjunta de Fiscalização e Atendimento', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (6, 'Fernando Salavracos Komatsu', 'Subsecretaria Adjunta de Gestão Tributária', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (7, 'Fabio Rocha Verbicario', 'Subsecretaria Adjunta de Política Tributária', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (8, 'Gabriel Mac Dowell Blum', 'Subsecretaria de Tecnologia da Informação e Comunicação', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (9, 'Rafaelle de Abreu Orlando', 'Subsecretaria Adjunta de Planejamento e Governança de Tecnologia da Informação e Comunicação', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (10, 'Tomaz Lucas Santos Leal', 'Subsecretaria do Tesouro do Estado do Rio de Janeiro', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (11, 'Diana Cabral Siqueira', 'Subsecretaria Adjunta de Finanças', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (12, 'Liliane Figueiredo', 'Subsecretaria Adjunta de Política Fiscal', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (13, 'Yasmim da Costa Monteiro', 'Subsecretaria Adjunta de Contabilidade', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (14, 'Raphael Antonio Nogueira', 'Subsecretaria Jurídica', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (15, 'Ana Luiza Pereira Lima', 'Subsecretaria de Controle Interno', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (16, 'Karine Tomaz Veiga', 'Subsecretaria de Administração', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (17, 'Marcelo Zenni Travassos', 'Corregedor Tributário de Controle Externo', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (18, 'Alvaro Marques Neto', 'Presidente do Conselho de Contribuintes', TRUNC(SYSDATE));
INSERT INTO COE_IA."IA0001_IOERJ_RAG_DIARIO_INTELIGENTE_002N" (ID, NOME, FUNCAO, DATA_INI) VALUES (19, 'Fernanda Calil Tannus de Oliveira', 'Ouvidor Geral, simbolo DG', TRUNC(SYSDATE));

COMMIT;
